### PR TITLE
Created new find account directive

### PR DESCRIPTION
**Pull request by jmcameron**
Created a new findAccount directive.

Updated the Report/Account Statement page to use the new directive.

I've added several options to the findAccount directive that should make it more useful in various contexts.  I addeda  documentation page in the client/src/js/directives folder:

  [findaccount.md](https://github.com/jmcameron/bhima/blob/feature/find_account_directive/client/src/js/directives/findaccount.md)

### CODE REVIEW

**Comment by jniles** [comment]
The code looks good to me. If someone else can verify that it behaves as expected, we can pull this in.

**Comment by jmcameron** [comment]
@DedrickEnc Please review this PR and if it is okay, merge into development.

**Comment by jniles** [comment]
@jmcameron It seems like the directive is a bit buggy.  Once a selection is chosen, you can search for another selection just fine ... however all the titles displayed are the selected account.  I've attached a screenshot to illustrate.

accountdirective

**Comment by jmcameron** [comment]
Strange... I am not seeing this issue at all.  You are using my branch feature/find_account_directive and it is up to date, right?

I tried searching for new accounts several times in a row and it worked fine each time for me.

**Comment by jniles** [comment]
Alright, I'll debug it on my machine and let you know.

**Comment by jniles** [comment]
More details:
I am using the latest pull from your branch.  On the report page, you can still use the text input after clicking "submit".  Is this expected behavior?  If you try to do execute a new search without hitting the "refresh" button, the screen shot is the result.

However, upon refresh, the whole directive works correctly.  My recommendation is that we either disable the search after an initial search, or we remove the "refresh" functionality and make the directive behave like the other "find" directives.

Can you reproduce the bug on your end?

**Comment by jmcameron** [comment]
Ok, I understand.  I never thought of that.  I always pressed the refresh button first.  I think I can fix that pretty easity.

**Comment by jmcameron** [comment]
I've fixed this issue.  Now after you select account (before you press [Submit]), the field becomes read-only.  So to select another account, you must press the refresh button.   And once you have pressed the [Submit] button, the field is cleared and the next search should work fine.    I played around with getting the form to clear itself if you click in the account field after an account is selected, but I could not get that to work properly.  I think this approach is reasonable.

NOTE:  Both my feature/edit_budget PR and this PR have exactly the same code relating to the new findAccount directive and the adaptation of the account statement report to use it.  Therefore, if the feature/edit_budget branch is merged in first, this PR can be closed.    If this PR is merged first, the feature/edit_budget branch is still needed even though it does include the changes in this PR.  The changes are identical, so I do not think it will cause any merge conflicts.

**Comment by jniles** [comment]
Alright, this behaves as expected for me.

**Pull request merged**
