### PR TITLE
Minors fixes in purchase order modules

### PR DESCRIPTION
**Pull request by DedrickEnc**
In this PR, I removed the ng-strict-di directive temporarily and fix some issue about date and so one ...

### CODE REVIEW

**Comment by jniles** [comment]
Didn't we discover that `ng-strict-di` wasn't the problem?  In fact, `ng-strict-di` pointed us to the solution. Why are you removing it?

**Comment by DedrickEnc** [comment]
Actually no, there are some module which break because of ng-strict-di.
I removed that temporarily, it can be added later.

**Comment by DedrickEnc** [comment]
@jniles this PR can be merged any time.

**Comment by jniles** [comment]
Looks good to me.  Thanks!

**Pull request merged**
