### PR TITLE
Update server npm dependencies for tshikaji installation

### PR DESCRIPTION
**Pull request by jniles**
In this PR:
 - `package.json` has been pruned significantly.  Only used dependencies are included.  Those required to run have been installed using `npm [package] --save` rather than `--save-development`.
 - The old server logger has been removed and replaced with [morgan](https://github.com/expressjs/morgan).

### CODE REVIEW

**Comment by jniles** [comment]
@DedrickEnc, would you mind reviewing this PR?

**Comment by DedrickEnc** [comment]
This PR brokes the server when merged.

module.js:340
    throw err;
          ^
Error: Cannot find module 'accepts'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kitamuka/DedrickEnc/bhima/node_modules/compression/index.js:15:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17).

I can not merge it in, please take the time to review it and give me a feedback.
Thanks.

**Comment by jniles** [comment]
Yes, that is because it removes deprecated functions and adds their replacement. After this is merged everyone has to run npm install to bring their repository up to date. This is a natural part of the upgrade process.

**Comment by jniles** [comment]
@DedrickEnc , when you get a chance, can you validate that this works correctly and merge it in?  To debug #299 and #301, we will want access to the morgan logger that is included in this PR.

**Comment by DedrickEnc** [comment]
Interest, because I taped the npm install command after merging it in, I will try again.
Sorry for the long absence, I was not abble to go to the office and the gouvernement locked the mobile internet for several days.

there was some troubles, but now every things seems fine.
Thanks

**Comment by jniles** [comment]
Alright, I'll investigate.

**Pull request closed without merging**
