### PR TITLE
Added CLA and contributing instructions

### PR DESCRIPTION
**Pull request by jniles**
In this PR:
 - established a system to accept contributions under license agreements
 - wrote limited contributing instructions
 - rm old documentation

### CODE REVIEW

**Comment by DedrickEnc** [comment]
Jonathan, there a bhima mail called bhimateam@gmail.com, you can take it instead of using the private email.

**Comment by jniles** [comment]
Okay, will make the relevant changes.

**Comment by jniles** [comment]
Email has been changed.  If you leave this PR open a few more days, I'll clean up the text.

**Comment by DedrickEnc** [comment]
Okay, I will leave it like this.

**Comment by jniles** [comment]
Alright, this is a good enough start.  You can merge it any time.

**Pull request merged**
