### PR TITLE
Added page to create/edit budgets

### PR DESCRIPTION
**Pull request by jmcameron**
Added a new page to create and edit budget data for individual accounts for a specific fiscal year.

WARNING: This addition requires adding a new database entry.  You can do that using this file:

     server/models/updates/2015-01-13-Add-budget-edit-menu.sql

NOTE: The English versions of the translation items have been copied to the fr.json file but have not been translated.  I've appended a '???' on the untranslated items.  I request help from @DedrickEnc or @mbayopanda or @lomamech with the translations.   Feel free to email them to me and I'll update the pull request.

### CODE REVIEW

**Comment by jmcameron** [comment]
NOTE: This PR depends on the 'Create New findAccount directive' and incorporates its changed into this PR.

**Comment by jmcameron** [comment]
Just realized that I have not restricted the searches to the current enterprise.  I'd like to get that fixed (today) before this PR is merged.

**Comment by jmcameron** [comment]
I've fixed the issue with restricting the budget creation/editing to the current enterprise.   So it is ready to go, as far as I'm concerned.

**Comment by jniles** [comment]
@jmcameron, I like where this is going.  However, it seems like there is quite a few features that will need to go in before this is stable enough to run in development.

I have made a separate branch off development called `feature/budget`.  Can you redirect your PR there?  We can all contribute with polishes, fixes, and new features until it is a full package to be merged into development.

**Comment by jmcameron** [comment]
I can merge this into feature/budget.  Why don't I merge the other budget one into it too.  They are independent of each other but both have to do with budget creation and analysis.

**Comment by jmcameron** [comment]
I can merge this into feature/budget.  Why don't I merge the other budget one into it too.  They are independent of each other but both have to do with budget creation and analysis.

**Comment by jniles** [comment]
That sounds perfect.

**Comment by jmcameron** [comment]
Redirected against feature/budget

**Pull request closed without merging**
