### PR TITLE
Rework logger for server

### PR DESCRIPTION
**Pull request by jniles**
This PR removes the logger.js and associated plugins from the server architecture.  For production environments, we should use a production-quality logger such as [morgan](https://github.com/expressjs/morgan).  Support for morgan will be added in a future commit.

### CODE REVIEW

**Comment by jniles** [comment]
@DedrickEnc , can you approve these changes?

**Comment by DedrickEnc** [comment]
I will see that

**Comment by jniles** [comment]
Will this even make it into production?  Asking for a friend.

**Comment by DedrickEnc** [comment]
It will be merged in the development branch after the trip.

**Pull request merged**
