### PR TITLE
Fix(Exchange rate) display correctly the exchange rate

### LINKED ISSUE #6056: Display correctly the exchange rate in the home page
As BHIMA supports multi-currency, the exchange rate disposition in the home page has been broken.

WhatsApp Image 2021-10-25 at 01 16 14

### PR DESCRIPTION
**Pull request by jeremielodi**
I propose to display the exchange rates as follow :

new_rate

closes #6056

### CODE REVIEW

**Review by jmcameron — COMMENTED** [review]
It seems to me that all currencies should be expressed in terms of the enterprise currency.  So for Bhima test, should it be something like:

  930 Fc = $1 USD
set on <date>

  0.84 eu = $1 USD
set on <date>

Similar to what you see on the exchange rate page...

**Comment by jeremielodi** [comment]
Thanks @jmcameron.

**Review by jmcameron — APPROVED** [review]
Thanks!  Looks good.

**Comment by jniles** [comment]
LGTM.

bors r+

**Pull request merged**
